package com.peerdsa.analytics;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import com.peerdsa.user.User;
import java.net.SocketTimeoutException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpStatus;
import org.springframework.web.client.HttpClientErrorException;
import org.springframework.web.client.HttpServerErrorException;
import org.springframework.web.client.ResourceAccessException;
import org.springframework.test.util.ReflectionTestUtils;
import org.springframework.web.server.ResponseStatusException;

/**
 * "Analytics is asleep" and "analytics is misconfigured" are different failures. Collapsing both
 * into 503 makes a wrong INTERNAL_TOKEN look like a cold start, and makes the client retry a
 * configuration error forever. The client retries 503 and only 503.
 */
class AnalyticsControllerTest {

    private AnalyticsService analytics;
    private AnalyticsController controller;
    private User user;

    @BeforeEach
    void setUp() {
        analytics = mock(AnalyticsService.class);
        controller = new AnalyticsController(analytics);
        user = new User();
        ReflectionTestUtils.setField(user, "id", 1L); // generated by the database; no setter

    }

    @Test
    void aTimeoutOrRefusedConnectionIsAretryable503() {
        when(analytics.weakness(anyLong()))
                .thenThrow(new ResourceAccessException("timeout", new SocketTimeoutException("read timed out")));

        assertThatThrownBy(() -> controller.weakness(user))
                .isInstanceOf(ResponseStatusException.class)
                .satisfies(e -> assertThat(((ResponseStatusException) e).getStatusCode())
                        .isEqualTo(HttpStatus.SERVICE_UNAVAILABLE));
    }

    /** A wrong INTERNAL_TOKEN. Retrying cannot fix it, so it must not be a 503. */
    @Test
    void a401FromAnalyticsIsANonRetryable502() {
        when(analytics.weakness(anyLong())).thenThrow(HttpClientErrorException.create(
                HttpStatus.UNAUTHORIZED, "Unauthorized", null, null, null));

        assertThatThrownBy(() -> controller.weakness(user))
                .isInstanceOf(ResponseStatusException.class)
                .satisfies(e -> assertThat(((ResponseStatusException) e).getStatusCode())
                        .isEqualTo(HttpStatus.BAD_GATEWAY));
    }

    /** A wrong ANALYTICS_BASE_URL: something answered, and it was not our service. */
    @Test
    void a404FromAnalyticsIsANonRetryable502() {
        when(analytics.reviseNext(anyLong())).thenThrow(
                HttpClientErrorException.create(HttpStatus.NOT_FOUND, "Not Found", null, null, null));

        assertThatThrownBy(() -> controller.reviseNext(user))
                .isInstanceOf(ResponseStatusException.class)
                .satisfies(e -> assertThat(((ResponseStatusException) e).getStatusCode())
                        .isEqualTo(HttpStatus.BAD_GATEWAY));
    }

    /** Analytics crashed. It answered, so it is reachable: still a 502, not a cold start. */
    @Test
    void a500FromAnalyticsIsA502NotA503() {
        when(analytics.weakness(anyLong())).thenThrow(HttpServerErrorException.create(
                HttpStatus.INTERNAL_SERVER_ERROR, "Boom", null, null, null));

        assertThatThrownBy(() -> controller.weakness(user))
                .isInstanceOf(ResponseStatusException.class)
                .satisfies(e -> assertThat(((ResponseStatusException) e).getStatusCode())
                        .isEqualTo(HttpStatus.BAD_GATEWAY));
    }

    /**
     * Measured against Render: a spun-down free-tier service does not time out. Its edge answers
     * with a gateway error in about a second. That is a cold start, it resolves itself, and the
     * client must retry it -- so it has to be a 503. Classifying it as 502 turned an ordinary
     * cold start into a permanent "analytics unavailable" panel on the dashboard.
     */
    @Test
    void aGatewayErrorFromRenderWhileAnalyticsWakesIsARetryable503() {
        for (HttpStatus gateway : new HttpStatus[] {
            HttpStatus.BAD_GATEWAY, HttpStatus.SERVICE_UNAVAILABLE, HttpStatus.GATEWAY_TIMEOUT
        }) {
            // doThrow, not when(...): re-stubbing with when() would CALL the already-stubbed
            // mock and throw the previous iteration's exception right here.
            doThrow(HttpServerErrorException.create(gateway, gateway.getReasonPhrase(), null, null, null))
                    .when(analytics)
                    .weakness(anyLong());

            assertThatThrownBy(() -> controller.weakness(user))
                    .describedAs("upstream %s must map to a retryable 503", gateway)
                    .isInstanceOf(ResponseStatusException.class)
                    .satisfies(e -> assertThat(((ResponseStatusException) e).getStatusCode())
                            .isEqualTo(HttpStatus.SERVICE_UNAVAILABLE));
        }
    }
}
